platform :ios, '9.3'

target 'MyPath' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SideMenu'
    pod 'Firebase/Core'

  target 'MyPathTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyPathUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
